name: CI
on: push

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase=123456 --output secrets.json secrets.json.gpg
        env:
          PASSPHRASE: $ {{ secrets.PASSPHRASE }}
      - name: Print our file content
        run: cat secrets.json

