#Lab feito com base no treinamento de Github Actions da Udemy.
#Precisa encriptar o arquivo e subir para o repositorio.
#Fonte: https://docs.github.com/en/actions/security-guides/encrypted-secrets
name: Lab Encrypt 
on: push

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output secrets.json secrets.json.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Print our file content
        run: cat secrets.json
      

