name: CI
on: push

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASES" --output $HOME/secrets.json secrets.json.gpg
        env:
          PASSPHRASE: $ {{ secrets.PASSPHRASES }}
      - name: Print our file content
        run: cat $HOME/secrets.json

